print('¿que sale del cruce de un mono y un patin?')
input()
print('un monopatin')
print('¿porque vuelan los pajaros pa\'l sur?')
input()
print('porque caminando tardarian muchisimo')
input()
print('¿en que se parece una familia, un bombero, un barco?')
input()
print('en que el bombero y el barco tienen casco')
input()
print('¿y la familia?', end='')
print('- bien gracias')
